# Added by OrbStack: command-line tools and integration
# This won't be added again if you remove it.
source ~/.orbstack/shell/init.zsh 2>/dev/null || :

source /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh

